name: CICD

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Start MySQL service
      - name: Start MySQL service
        run: |
          sudo systemctl start mysql
          sudo mysqladmin --user=root --password=root ping

      # Set up MySQL root password and create test database
      - name: Set up MySQL Database
        run: |
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS restaurants;"
          sudo mysql --user=root --password=root -e "SHOW DATABASES;"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Run the tests (using MySQL connection details)
      - name: Run tests
        env:
          DATABASE_NAME: restaurants
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: root
          DATABASE_ENDPOINT: 127.0.0.1 # Use 127.0.0.1 for TCP connection
        run: |
          # Run database migrations
          python manage.py migrate
          
          # Run the tests
          python manage.py test
