name: CICD

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      # Install MySQL
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysqladmin --silent --wait=30 ping || exit 1

      # Set up MySQL with a new user
      - name: Set up MySQL User and Database
        run: |
          sudo mysql -e "CREATE USER 'ci_user'@'localhost' IDENTIFIED BY 'ci_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'ci_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS restaurants;"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4

      # Install dependencies
      - name: Install packages
        run: make install 

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          until mysql -u ci_user -pci_password -e "SHOW DATABASES;" 2>/dev/null; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Format code
      - name: Format code
        run: make format

      # Lint code
      - name: Lint code
        run: make lint

      # Run tests
      - name: Run tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_password
          MYSQL_DB: restaurants
        run: make test

      # Generate output
      - name: Generate output
        run: make generate
