name: CICD

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Start MySQL service
      - name: Start MySQL service
        run: |
          sudo systemctl start mysql
          sudo mysqladmin --user=root --password=root ping

      # Set up MySQL root password and create test database
      - name: Set up MySQL Database
        run: |
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS restaurants;"
          sudo mysql --user=root --password=root -e "SHOW DATABASES;"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install Python dependencies using Makefile
      - name: Install Python dependencies
        run: make install

      # Wait for MySQL to be ready (using root credentials)
      - name: Wait for MySQL to be ready
        run: |
          until mysql -u root -proot -e "SHOW DATABASES;" 2>/dev/null; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Format the code using Makefile
      - name: Format code
        run: make format

      # Lint the code using Makefile
      - name: Lint code
        run: make lint

      # Run tests using Makefile
      - name: Run tests
        run: make test

      # Generate output (if applicable)
      - name: Generate output
        run: make generate
