name: CICD

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Start MySQL service and configure a new user
      - name: Start MySQL and create new MySQL user
        run: |
          sudo systemctl start mysql
          # Create a new MySQL user with password authentication
          sudo mysql -e "CREATE USER IF NOT EXISTS 'ci_user'@'localhost' IDENTIFIED BY 'ci_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'ci_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS restaurants;"
          # Check the databases to ensure MySQL is running
          sudo mysql -e "SHOW DATABASES;"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Wait for MySQL to be ready (using new user)
      - name: Wait for MySQL to be ready
        run: |
          until mysql -u ci_user -pci_password -e "SHOW DATABASES;" 2>/dev/null; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Format the code using Makefile
      - name: Format code
        run: make format

      # Lint the code using Makefile
      - name: Lint code
        run: make lint

      # Run tests using Makefile
      - name: Run tests
        run: make test

      # Generate output (if applicable)
      - name: Generate output
        run: make generate
