name: CICD

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Jourdan980803..
          MYSQL_DATABASE: restaurants
        options: > 
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install packages
        run: make install 

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -P 3306 -u root -pJourdan980803.. -e "SHOW DATABASES;" 2>/dev/null; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Format code
        run: make format

      - name: Lint code
        run: make lint

      - name: Run tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: Jourdan980803..
          MYSQL_DB: restaurants
        run: make test

      - name: Generate output
        run: make generate
